#! /bin/sh

set -e

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi



SERVICES="
    "
INSTSERVICES="
    $(awk -F ":" '$3 >= 1000 {print "dropbox@"$1".service"}' /etc/passwd) 
    "

case "$1" in
    purge)
	if [ -x "/usr/bin/deb-systemd-helper-new" ]; then
		deb-systemd-helper-new purge $SERVICES $INSTSERVICES >/dev/null
		deb-systemd-helper-new unmask $SERVICES $INSTSERVICES >/dev/null
	fi
        ;;
    abort-upgrade)
        ;;
    remove)
        if [ -x "/usr/bin/deb-systemd-helper-new" ]; then
                deb-systemd-helper-new mask $SERVICES $INSTSERVICES >/dev/null
        fi
        ;;
    upgrade|failed-upgrade|abort-install|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
        ;;

esac
